# Generated by Django 5.0.1 on 2024-02-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/images/avatar.png', upload_to='users/images'),
        ),
    ]
