# Generated by Django 5.0.1 on 2024-02-27 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name': 'Permissions', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AddField(
            model_name='permissions',
            name='category',
            field=models.CharField(choices=[('Vendor Management', 'Vendor Management'), ('Product Management', 'Product Management'), ('Manage User Permissions', 'Manage User Permissions')], default='Product Management', max_length=50),
        ),
        migrations.AddField(
            model_name='permissions',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
